### ISSUE TITLE
Упрощение  HTML

### ISSUE THREAD

**Issue by Aleksei11** [Bohdan159/PropertyCross#1]
https://github.com/Bohdan159/PropertyCross/blob/0970f30bd5b81f172d490cd6c84ad1b2b0043367/src/app/header/header.component.html#L2

Попробуй унифицировать header. Сhange location брать по ивентам роутера, и заменить ngSwitch на ngIf(то о чем говорили)

**Comment by Bohdan159** [comment]
Fix
